// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package logger

import (
	"context"
	"sync"
)

// Ensure, that LoggerMock does implement Logger.
// If this is not the case, regenerate this file with moq.
var _ Logger = &LoggerMock{}

// LoggerMock is a mock implementation of Logger.
//
//	func TestSomethingThatUsesLogger(t *testing.T) {
//
//		// make and configure a mocked Logger
//		mockedLogger := &LoggerMock{
//			DebugFunc: func(msg string, args ...any)  {
//				panic("mock out the Debug method")
//			},
//			DebugContextFunc: func(ctx context.Context, msg string, args ...any)  {
//				panic("mock out the DebugContext method")
//			},
//			ErrorFunc: func(msg string, args ...any)  {
//				panic("mock out the Error method")
//			},
//			ErrorContextFunc: func(ctx context.Context, msg string, args ...any)  {
//				panic("mock out the ErrorContext method")
//			},
//			InfoFunc: func(msg string, args ...any)  {
//				panic("mock out the Info method")
//			},
//			InfoContextFunc: func(ctx context.Context, msg string, args ...any)  {
//				panic("mock out the InfoContext method")
//			},
//			WarnFunc: func(msg string, args ...any)  {
//				panic("mock out the Warn method")
//			},
//			WarnContextFunc: func(ctx context.Context, msg string, args ...any)  {
//				panic("mock out the WarnContext method")
//			},
//		}
//
//		// use mockedLogger in code that requires Logger
//		// and then make assertions.
//
//	}
type LoggerMock struct {
	// DebugFunc mocks the Debug method.
	DebugFunc func(msg string, args ...any)

	// DebugContextFunc mocks the DebugContext method.
	DebugContextFunc func(ctx context.Context, msg string, args ...any)

	// ErrorFunc mocks the Error method.
	ErrorFunc func(msg string, args ...any)

	// ErrorContextFunc mocks the ErrorContext method.
	ErrorContextFunc func(ctx context.Context, msg string, args ...any)

	// InfoFunc mocks the Info method.
	InfoFunc func(msg string, args ...any)

	// InfoContextFunc mocks the InfoContext method.
	InfoContextFunc func(ctx context.Context, msg string, args ...any)

	// WarnFunc mocks the Warn method.
	WarnFunc func(msg string, args ...any)

	// WarnContextFunc mocks the WarnContext method.
	WarnContextFunc func(ctx context.Context, msg string, args ...any)

	// calls tracks calls to the methods.
	calls struct {
		// Debug holds details about calls to the Debug method.
		Debug []struct {
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// DebugContext holds details about calls to the DebugContext method.
		DebugContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// Error holds details about calls to the Error method.
		Error []struct {
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// ErrorContext holds details about calls to the ErrorContext method.
		ErrorContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// Info holds details about calls to the Info method.
		Info []struct {
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// InfoContext holds details about calls to the InfoContext method.
		InfoContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// Warn holds details about calls to the Warn method.
		Warn []struct {
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// WarnContext holds details about calls to the WarnContext method.
		WarnContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
	}
	lockDebug        sync.RWMutex
	lockDebugContext sync.RWMutex
	lockError        sync.RWMutex
	lockErrorContext sync.RWMutex
	lockInfo         sync.RWMutex
	lockInfoContext  sync.RWMutex
	lockWarn         sync.RWMutex
	lockWarnContext  sync.RWMutex
}

// Debug calls DebugFunc.
func (mock *LoggerMock) Debug(msg string, args ...any) {
	if mock.DebugFunc == nil {
		panic("LoggerMock.DebugFunc: method is nil but Logger.Debug was just called")
	}
	callInfo := struct {
		Msg  string
		Args []any
	}{
		Msg:  msg,
		Args: args,
	}
	mock.lockDebug.Lock()
	mock.calls.Debug = append(mock.calls.Debug, callInfo)
	mock.lockDebug.Unlock()
	mock.DebugFunc(msg, args...)
}

// DebugCalls gets all the calls that were made to Debug.
// Check the length with:
//
//	len(mockedLogger.DebugCalls())
func (mock *LoggerMock) DebugCalls() []struct {
	Msg  string
	Args []any
} {
	var calls []struct {
		Msg  string
		Args []any
	}
	mock.lockDebug.RLock()
	calls = mock.calls.Debug
	mock.lockDebug.RUnlock()
	return calls
}

// DebugContext calls DebugContextFunc.
func (mock *LoggerMock) DebugContext(ctx context.Context, msg string, args ...any) {
	if mock.DebugContextFunc == nil {
		panic("LoggerMock.DebugContextFunc: method is nil but Logger.DebugContext was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Msg  string
		Args []any
	}{
		Ctx:  ctx,
		Msg:  msg,
		Args: args,
	}
	mock.lockDebugContext.Lock()
	mock.calls.DebugContext = append(mock.calls.DebugContext, callInfo)
	mock.lockDebugContext.Unlock()
	mock.DebugContextFunc(ctx, msg, args...)
}

// DebugContextCalls gets all the calls that were made to DebugContext.
// Check the length with:
//
//	len(mockedLogger.DebugContextCalls())
func (mock *LoggerMock) DebugContextCalls() []struct {
	Ctx  context.Context
	Msg  string
	Args []any
} {
	var calls []struct {
		Ctx  context.Context
		Msg  string
		Args []any
	}
	mock.lockDebugContext.RLock()
	calls = mock.calls.DebugContext
	mock.lockDebugContext.RUnlock()
	return calls
}

// Error calls ErrorFunc.
func (mock *LoggerMock) Error(msg string, args ...any) {
	if mock.ErrorFunc == nil {
		panic("LoggerMock.ErrorFunc: method is nil but Logger.Error was just called")
	}
	callInfo := struct {
		Msg  string
		Args []any
	}{
		Msg:  msg,
		Args: args,
	}
	mock.lockError.Lock()
	mock.calls.Error = append(mock.calls.Error, callInfo)
	mock.lockError.Unlock()
	mock.ErrorFunc(msg, args...)
}

// ErrorCalls gets all the calls that were made to Error.
// Check the length with:
//
//	len(mockedLogger.ErrorCalls())
func (mock *LoggerMock) ErrorCalls() []struct {
	Msg  string
	Args []any
} {
	var calls []struct {
		Msg  string
		Args []any
	}
	mock.lockError.RLock()
	calls = mock.calls.Error
	mock.lockError.RUnlock()
	return calls
}

// ErrorContext calls ErrorContextFunc.
func (mock *LoggerMock) ErrorContext(ctx context.Context, msg string, args ...any) {
	if mock.ErrorContextFunc == nil {
		panic("LoggerMock.ErrorContextFunc: method is nil but Logger.ErrorContext was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Msg  string
		Args []any
	}{
		Ctx:  ctx,
		Msg:  msg,
		Args: args,
	}
	mock.lockErrorContext.Lock()
	mock.calls.ErrorContext = append(mock.calls.ErrorContext, callInfo)
	mock.lockErrorContext.Unlock()
	mock.ErrorContextFunc(ctx, msg, args...)
}

// ErrorContextCalls gets all the calls that were made to ErrorContext.
// Check the length with:
//
//	len(mockedLogger.ErrorContextCalls())
func (mock *LoggerMock) ErrorContextCalls() []struct {
	Ctx  context.Context
	Msg  string
	Args []any
} {
	var calls []struct {
		Ctx  context.Context
		Msg  string
		Args []any
	}
	mock.lockErrorContext.RLock()
	calls = mock.calls.ErrorContext
	mock.lockErrorContext.RUnlock()
	return calls
}

// Info calls InfoFunc.
func (mock *LoggerMock) Info(msg string, args ...any) {
	if mock.InfoFunc == nil {
		panic("LoggerMock.InfoFunc: method is nil but Logger.Info was just called")
	}
	callInfo := struct {
		Msg  string
		Args []any
	}{
		Msg:  msg,
		Args: args,
	}
	mock.lockInfo.Lock()
	mock.calls.Info = append(mock.calls.Info, callInfo)
	mock.lockInfo.Unlock()
	mock.InfoFunc(msg, args...)
}

// InfoCalls gets all the calls that were made to Info.
// Check the length with:
//
//	len(mockedLogger.InfoCalls())
func (mock *LoggerMock) InfoCalls() []struct {
	Msg  string
	Args []any
} {
	var calls []struct {
		Msg  string
		Args []any
	}
	mock.lockInfo.RLock()
	calls = mock.calls.Info
	mock.lockInfo.RUnlock()
	return calls
}

// InfoContext calls InfoContextFunc.
func (mock *LoggerMock) InfoContext(ctx context.Context, msg string, args ...any) {
	if mock.InfoContextFunc == nil {
		panic("LoggerMock.InfoContextFunc: method is nil but Logger.InfoContext was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Msg  string
		Args []any
	}{
		Ctx:  ctx,
		Msg:  msg,
		Args: args,
	}
	mock.lockInfoContext.Lock()
	mock.calls.InfoContext = append(mock.calls.InfoContext, callInfo)
	mock.lockInfoContext.Unlock()
	mock.InfoContextFunc(ctx, msg, args...)
}

// InfoContextCalls gets all the calls that were made to InfoContext.
// Check the length with:
//
//	len(mockedLogger.InfoContextCalls())
func (mock *LoggerMock) InfoContextCalls() []struct {
	Ctx  context.Context
	Msg  string
	Args []any
} {
	var calls []struct {
		Ctx  context.Context
		Msg  string
		Args []any
	}
	mock.lockInfoContext.RLock()
	calls = mock.calls.InfoContext
	mock.lockInfoContext.RUnlock()
	return calls
}

// Warn calls WarnFunc.
func (mock *LoggerMock) Warn(msg string, args ...any) {
	if mock.WarnFunc == nil {
		panic("LoggerMock.WarnFunc: method is nil but Logger.Warn was just called")
	}
	callInfo := struct {
		Msg  string
		Args []any
	}{
		Msg:  msg,
		Args: args,
	}
	mock.lockWarn.Lock()
	mock.calls.Warn = append(mock.calls.Warn, callInfo)
	mock.lockWarn.Unlock()
	mock.WarnFunc(msg, args...)
}

// WarnCalls gets all the calls that were made to Warn.
// Check the length with:
//
//	len(mockedLogger.WarnCalls())
func (mock *LoggerMock) WarnCalls() []struct {
	Msg  string
	Args []any
} {
	var calls []struct {
		Msg  string
		Args []any
	}
	mock.lockWarn.RLock()
	calls = mock.calls.Warn
	mock.lockWarn.RUnlock()
	return calls
}

// WarnContext calls WarnContextFunc.
func (mock *LoggerMock) WarnContext(ctx context.Context, msg string, args ...any) {
	if mock.WarnContextFunc == nil {
		panic("LoggerMock.WarnContextFunc: method is nil but Logger.WarnContext was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Msg  string
		Args []any
	}{
		Ctx:  ctx,
		Msg:  msg,
		Args: args,
	}
	mock.lockWarnContext.Lock()
	mock.calls.WarnContext = append(mock.calls.WarnContext, callInfo)
	mock.lockWarnContext.Unlock()
	mock.WarnContextFunc(ctx, msg, args...)
}

// WarnContextCalls gets all the calls that were made to WarnContext.
// Check the length with:
//
//	len(mockedLogger.WarnContextCalls())
func (mock *LoggerMock) WarnContextCalls() []struct {
	Ctx  context.Context
	Msg  string
	Args []any
} {
	var calls []struct {
		Ctx  context.Context
		Msg  string
		Args []any
	}
	mock.lockWarnContext.RLock()
	calls = mock.calls.WarnContext
	mock.lockWarnContext.RUnlock()
	return calls
}
